export default {
  FETCH_COLLECTION: 'app/MainLayout/FETCH_COLLECTION',
  FETCH_COLLECTION_REQUEST: 'app/MainLayout/FETCH_COLLECTION_REQUEST',
  FETCH_COLLECTION_SUCCESS: 'app/MainLayout/FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILURE: 'app/MainLayout/FETCH_COLLECTION_FAILURE',
  ADD_FAVORITE: 'app/MainLayout/ADD_FAVORITE',
  ADD_FAVORITE_REQUEST: 'app/MainLayout/ADD_FAVORITE_REQUEST',
  ADD_FAVORITE_SUCCESS: 'app/MainLayout/ADD_FAVORITE_SUCCESS',
  ADD_FAVORITE_FAILURE: 'app/MainLayout/ADD_FAVORITE_FAILURE',
  EDIT_ITEM: 'app/MainLayout/EDIT_ITEM',
  EDIT_ITEM_REQUEST: 'app/MainLayout/EDIT_ITEM_REQUEST',
  EDIT_ITEM_SUCCESS: 'app/MainLayout/EDIT_ITEM_SUCCESS',
  EDIT_ITEM_FAILURE: 'app/MainLayout/EDIT_ITEM_FAILURE',
  DELETE_ITEM: 'app/MainLayout/DELETE_ITEM',
  DELETE_ITEM_REQUEST: 'app/MainLayout/DELETE_ITEM_REQUEST',
  DELETE_ITEM_SUCCESS: 'app/MainLayout/DELETE_ITEM_SUCCESS',
  DELETE_ITEM_FAILURE: 'app/MainLayout/DELETE_ITEM_FAILURE'
};
